---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - githubreleases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - githubreleases/finalizers
  verbs:
  - update
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - githubreleases/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - githubreleasesmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - secrets/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cvemonitor.csye7125-su24-team17.com
  resources:
  - secrets/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
